
spring:
   rabbitmq:
     host: 192.168.117.132
     port: 5672
     username: admin
     password: admin
     publisher-confirms: true
     listener:
       simple:
         concurrency: 10
         max-concurrency: 20
         prefetch: 5
demo:
  rabbitmq:
    config:
      model: 1
server:
  port: 9999