
spring:
   rabbitmq:
     host: 192.168.1.11
     port: 5672
     username: admin
     password: admin
     publisher-confirms: true

demo:
  rabbitmq:
    config:
      model: 2
server:
  port: 9999