spring:
   rabbitmq:
     host: 192.168.1.11
     port: 5672
     username: admin
     password: admin
     publisher-confirms: true
     listener:
       simple:
         concurrency: 10
         max-concurrency: 20
         prefetch: 5
         acknowledge-mode: manual   #手动确认
demo:
  rabbitmq:
    config:
      model: 2
server:
  port: 8889