spring:
   rabbitmq:
     host: 192.168.117.132
     port: 5672
     username: admin
     password: admin
     listener:
       simple:
         concurrency: 10
         max-concurrency: 20
         prefetch: 5

    #     acknowledge-mode: manual   #手动确认
demo:
  rabbitmq:
    config:
      model: 5
server:
  port: 8888